apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-check-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-check-service
  template:
    metadata:
      name: credit-check-pod
      labels:
        app: credit-check-service
    spec:
      nodeSelector:
        node-type: private
      containers:
        - name: credit-check-service
          image: anubhav83/credit-check-service:v6
          ports:
            - containerPort: 2112
          livenessProbe:
            httpGet:
              path: "/api/v1/health"
              port: 2112
            initialDelaySeconds: 5
            periodSeconds: 30
