apiVersion: v1
kind: Service
metadata:
  name: decision-service-nodeport
  labels:
    operation: nodePortService
spec:
  type: NodePort
  selector:
    app: decision-service-pod
  ports:
    - port: 2212
      targetPort: 2212
      nodePort: 30956